import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import "./globals.css";
import Container from "@/components/ui/Container";
import MainNav from "@/components/ui/Navbar/MainNav";

const  font = Poppins({weight:['400','200','300','500','600','700','800','900'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        
       <Container>
       <MainNav/>
        {children}
       </Container>
        </body>
    </html>
  );
}
